name: Youtube Bot Runner
on:
  workflow_dispatch: # Allows you to start it with a button
  schedule:
    - cron: '0 */6 * * *' # Automatically runs every 6 hours

jobs:
  run-bot:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Tools
        run: |
          pip install playwright gspread google-auth requests
          playwright install chromium
      - name: Execute Bot
        env:
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          FIXED_PASSWORD: ${{ secrets.FIXED_PASSWORD }}
        run: python bot.py
